"""
Phase 5 — Weekly Pulse Note Builder

Renders the weekly pulse note from theme analysis results using a Jinja2
template.  Enforces a ≤250-word limit by iteratively trimming the longest
action idea description.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional

from jinja2 import Environment, FileSystemLoader

# Template lives next to this module
_TEMPLATE_DIR = Path(__file__).parent / "templates"


def _word_count(text: str) -> int:
    """Return the number of words in *text*."""
    return len(text.split())


def _trim_actions(actions: List[str], max_words: int = 15) -> List[str]:
    """Shorten each action idea to at most *max_words* words."""
    trimmed = []
    for a in actions:
        words = a.split()
        if len(words) > max_words:
            trimmed.append(" ".join(words[:max_words]) + "…")
        else:
            trimmed.append(a)
    return trimmed


def build_pulse_note(
    themes: List[Dict],
    actions: List[str],
    review_count: int,
    week_date: Optional[str] = None,
) -> str:
    """
    Render the Jinja2 pulse note template and enforce the ≤250-word limit.

    Parameters
    ----------
    themes : list[dict]
        Each dict must have keys: ``theme``, ``summary``, ``quote``.
    actions : list[str]
        Three action ideas generated by the LLM.
    review_count : int
        Total number of reviews that were analysed.
    week_date : str | None
        Human-readable week string (defaults to today's date).

    Returns
    -------
    str
        Rendered Markdown pulse note (≤250 words).
    """
    if week_date is None:
        week_date = datetime.now().strftime("%Y-%m-%d")

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        keep_trailing_newline=True,
    )
    template = env.get_template("pulse_note.md.j2")

    # Iteratively trim actions until ≤250 words
    current_actions = list(actions)
    max_trim_words = 20  # start generous, shrink if needed

    for _ in range(10):  # safety cap
        rendered = template.render(
            week_date=week_date,
            review_count=review_count,
            top_themes=themes,
            actions=current_actions,
            generated_at=generated_at,
        )
        wc = _word_count(rendered)
        if wc <= 250:
            break
        # trim the longest action first
        max_trim_words = max(max_trim_words - 3, 5)
        current_actions = _trim_actions(current_actions, max_words=max_trim_words)
    else:
        # Last resort: truncate the whole note
        words = rendered.split()[:250]
        rendered = " ".join(words)

    return rendered
